wandb_version: 1
undersample:
  value: True
tokenizer:
  value: 'distilbert-base-cased'
dataset:
  value: 'wikipedia_comments'
model_name:
  value: 'distilbert-base-cased'
optimizer:
  value: 'adam'
epochs:
  value: 3
batch_size:
  value: 8
seq_length_max:
  value: 500
train_size_max:
  value: 5000
val_size_max:
  value: 1000000
lr:
  value: 0.00001
learning_rate_decay_schedule:
  value: 'linear'
freeze_encoder:
  value: False
