undersample:
  value: True
tokenizer:
  value: 'bert-base-uncased'
dataset:
  value: 'wikipedia_comments'
model_name:
  value: 'simple_rnn'
optimizer:
  value: 'rmsprop'
epochs:
  value: 20
batch_size:
  value: 8
max_seq_length:
  value: 300
max_train_size:
  value: 100
max_val_size:
  value: 100
lr:
  value: 0.01
