wandb_version: 1
undersample:
  value: True
tokenizer:
  value: 'bert-base-uncased'
dataset:
  value: 'wikipedia_comments'
model_name:
  value: 'simple_rnn'
optimizer:
  value: 'rmsprop'
epochs:
  value: 10
batch_size:
  value: 8
max_seq_length:
  value: 100
max_train_size:
  value: 24
max_val_size:
  value: 24
lr:
  value: 0.01
log:
  value: null
learning_rate_decay_schedule:
  value: null
log_freq:
  value: null
checkpoint_metric:
  value: 'auc'
