undersample:
  value: False
tokenizer:
  value: 'xlnet-base-cased'
dataset:
  value: 'wikipedia_comments'
model_name:
  value: 'xlnet-base-cased'
optimizer:
  value: 'adam'
epochs:
  value: 4
batch_size:
  value: 8
max_seq_length:
  value: 300
max_train_size:
  value: 100
max_val_size:
  value: 100
lr:
  value: 0.000005
