undersample:
  value: False
tokenizer:
  value: 'xlnet-base-cased'
dataset:
  value: 'wikipedia_comments'
model_name:
  value: 'xlnet-base-cased'
optimizer:
  value: 'adam'
epochs:
  value: 4
batch_size:
  value: 4
seq_length_max:
  value: 300
train_size_max:
  value: 1000000
val_size_max:
  value: 1000000
lr:
  value: 0.00005
